CREATE TABLE CUSTOMERS
  (
    CUSTOMERNUMBER         NUMBER NOT NULL PRIMARY KEY,
    CUSTOMERNAME           VARCHAR2(50),
    CONTACTLASTNAME        VARCHAR2(30),
    CONTACTFIRSTNAME       VARCHAR2(30),
    PHONE                  VARCHAR2(15),
    ADDRESSLINE1           VARCHAR2(50),
    ADDRESSLINE2           VARCHAR2(50),
    CITY                   VARCHAR2(20),
    STATE                  VARCHAR2(20),
    POSTALCODE             NUMBER,
    COUNTRY                VARCHAR2(20),
    SALESREPEMPLOYEENUMBER NUMBER,
    CREDITLIMIT            NUMBER
  );
DROP TABLE CUSTOMERS;
CREATE TABLE EMPLOYEES
  (
    EMPLOYEENUMBER NUMBER NOT NULL PRIMARY KEY,
    LASTNAME       VARCHAR2(20),
    FIRSTNAME      VARCHAR2(20),
    EXTENSION      NUMBER,
    EMAIL          VARCHAR2(40),
    OFFICECODE     NUMBER,
    REPORTSTO      VARCHAR2(30),
    JOBTITLE       VARCHAR2(20)
  );
CREATE TABLE OFFICES
  (
    OFFICECODE   NUMBER NOT NULL PRIMARY KEY,
    CITY         VARCHAR2(30),
    PHONE        NUMBER,
    ADDRESSLINE1 VARCHAR2(50),
    ADDRESSLINE2 VARCHAR2(50),
    STATE        VARCHAR2(20),
    COUNTRY      VARCHAR2(30),
    POSTALCODE   NUMBER,
    TERRITORY    VARCHAR2(30)
  );
  
CREATE TABLE 